### ISSUE TITLE
Router breaks globals

### ISSUE THREAD

**Issue by dontcallmedom** [tiger-seo/PhpBuiltinServer#14]
Because the scripts (or the user-provided router) is included inside a function, the variable globals that these scripts might be relying on setting and reading are no longer visible in the global space.

**Comment by scottaubrey** [comment]
Agreed, the wrapper Router completely breaks our setup where all dev is done using the builtin server

To get ours going, I either have to:

- replace the line  `__DIR__.'/'.Router.php` with the `$this->config['router']` in the extension class
    - the access log stuff never fires under this scenario
- run the contents of `Router::main()` in global scope **and** switch the if block so that test for $userRouter is entered first.
    - we have routable php scripts in the public directory that our own customer router performs some black magic to run, Router.php just returns the file path without invoking our router.

For now, I've copied both into our project to run as an extension in our namespace, and I've chosen the changes from second option from above.
